const express = require('express');
const URL = require('../models/url')
const router = express.Router();

// homepage here we are fetching all routes but we want the current user routes only
router.get("/", async(req,res)=> {
    if(!req.user) return res.redirect('/login')
    const allUrls = await URL.find({ createdBy: req.user._id }); // now we will get the urls only generated by a user

    return res.render("home", {
        urls: allUrls,
    });
});

router.get("/signup", async(req,res)=> {
    return res.render("signup");
});
// to show login page on ui
router.get("/login", async(req,res)=> {
    return res.render("login");
});

module.exports = router;


